blank_issues_enabled: false
contact_links:
- name: Example Link 1
  about: An example for linking to anywhere needed, may instructions/guides? (Internal links also valid)
  url: https://www.geaerospace.com/
- name: Example Link 2
  about: Another example link
  url: https://www.ge.com/