name: Handle Issues
on:
  issues:
#     types:
#       - edited
#       - labeled
#       (and more!)
  workflow_dispatch: # This may not work for Issue events
  
# permissions:
#   contents: read
#   issues: write

jobs:
  assign-unassigned:
    if: | # Nobody is assigned && not closed
      join(github.event.issue.assignees) == '' &&
      !(contains(github.event.issue.labels.*.name, 'status/closed'))
    runs-on: ubuntu-latest
    steps:
      - run: gh issue edit $ISSUE --add-assignee 'WilliamMiceli'
        env:
          GH_TOKEN: ${{ secrets.WILLIAM_ORG_PAT }}
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}


#### Transferring Issues
# These must be the last step, as after being transferred, the issue reference will no longer be valid

  transfer-problem-reports-to-repository:
    if: | # Problem reports that have been triaged
      contains(github.event.issue.labels.*.name, 'type/problem-report') &&
      contains(github.event.issue.labels.*.name, 'status/assigned') &&
      !(contains(github.event.issue.labels.*.name, 'status/closed'))
    runs-on: ubuntu-latest
    steps:
      - run: gh issue transfer $ISSUE $TARGET_REPO
        env:
          GH_TOKEN: ${{ secrets.WILLIAM_ORG_PAT }}
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
          TARGET_REPO: https://github.com/This-Is-Only-A-Test-123/650XXX-Widget-FBT # Eventually this will extract the repository name from the issue itself.


# Expressions: https://docs.github.com/en/actions/learn-github-actions/expressions
# Big example: https://docs.github.com/en/actions/examples/using-the-github-cli-on-a-runner
